### ISSUE TITLE
JOAD: Past pinshoots have dissapeared

### ISSUE THREAD

**Issue by Silventar** [s-amundson/wpa_2p1#102]
**Describe the bug**
The list of past pinshoots have dissapeared. See the photo.

**Expected behavior**
Previously, past pinshoots were listed with the current and upcoming shoots. These have dissapeared. I like the uncluttered table, but a link below the table to a list of past pinshoots should be included so we can maek pins received for past shoots when a parent pays late.

(Side note: it would be nice if past JOAD sessions also had la link below thebsessions table so the main table only shows current and future sessions.)

**Screenshots**
![Screenshot_20220816-183613_Chrome.jpg](https://user-images.githubusercontent.com/17868374/185015865-23f01aa2-eaa4-427c-9a61-4f054f819f86.jpg)

**Comment by s-amundson** [comment]
made views for past sessions as well as past events and added links for them.
