### ISSUE TITLE
Instructor info in Profile

### ISSUE THREAD

**Issue by Kathleenlangley** [s-amundson/wpa_2p1#103]
**Describe the bug**
I could not update my instructor information so it won't let me sign up for classes. Andrew put in the expiration dates. Neither of us could change the level. The latest expiration year is also only two years from now.  

[![image](https://user-images.githubusercontent.com/108587593/186270737-eab68af4-ef1a-43e4-b51a-82656ebe7924.png)]()

**Comment by s-amundson** [comment]
corrected issue to allow user to change, also updated year range to include 3 years.
