### ISSUE TITLE
Edit button on student page does notbwork

### ISSUE THREAD

**Issue by Silventar** [s-amundson/wpa_2p1#113]
**Describe the bug**
After searching for a student, the edit button does not work. I have tried on desktop and mobile see attached mobile  screenshot.
![Screenshot_20221108-124454_Chrome.jpg](https://user-images.githubusercontent.com/17868374/200671938-ebf2797f-e500-407d-a843-b8e470114203.jpg)

**Comment by s-amundson** [comment]
Found and resolved issue.
