### ISSUE TITLE
Merge students (admin feature)

Mari has two entries under Masako. (See attached inage) Can you create a way to merge students for admission only?

### ISSUE THREAD

**Issue by Silventar** [s-amundson/wpa_2p1#119]
Edited: removed image for privacy.

**Comment by Silventar** [comment]
We have another occurrence of students who need to be merged.

Cindy and Orion need to be merged. They are kids under a parent account. Orion has a safety class date but Cindy does not. Orion is also. JOAD Student.

![Screenshot_20230620-171716_Chrome.jpg](https://github.com/s-amundson/wpa_2p1/assets/17868374/df14cc43-34de-41bb-bb55-3051bf2e28a3)

**Comment by s-amundson** [comment]
student's can be deleted by user and/or board.
