### ISSUE TITLE
".com" does not redirect to ".org"

### ISSUE THREAD

**Issue by Alindah** [s-amundson/wpa_2p1#140]
**Describe the bug**
Visiting the website via "woodleyparkarchers.com" should automatically redirect to the ".org" version; however, this is not the case. While most pages appear to work as they should, the user will encounter a "403 Forbidden" page (at URL: https://woodleyparkarchers.com/recaptcha/) when attempting to access the login page.

**To Reproduce**
1. Go to https://woodleyparkarchers.com/
2. Click "Login" on the upper right corner.
3. You will encounter the 403 Forbidden page with the text, "CSRF verification failed. Request aborted."

**Expected behavior**
Upon visiting the ".com" version of the site, we should be taken to the ".org" version instead. We should be able to log in as normal.

**Desktop (please complete the following information):**
 - OS: macOS - Version 14.5 (Build 23F79)
 - Browser: Google Chrome - Version 126.0.6478.62 (Official Build) (arm64)

**Comment by s-amundson** [comment]
reconfigured nginx to redirect properly.
