### ISSUE TITLE
Edit button on student details page post search does not work.

### ISSUE THREAD

**Issue by Silventar** [s-amundson/wpa_2p1#29]
**Bug Description**
When an instructor level user presses the edit button on a students page, it fails to move to the edit page. (Edit button does not work.)

**To Reproduce**

1. Click Board Links
2. Click Search
3. Enter student, name press Submit
4. Click on student's last name
5. Press Edit next to students name

**Expected behavior**
Clicking edit should proceed to the next page to allow editing of the students name and safety class date.

**Screenshots**
![Screenshot_20220108-152324_Chrome.jpg](https://user-images.githubusercontent.com/17868374/148663280-2816e27d-9983-45a4-bc56-516d15879b40.jpg)If applicable, add screenshots to help explain your problem.

**Smartphone (please complete the following information):**
 - Device: Samsung Note 10+ (SM-N975U)
 - OS: Android 11
 - Browser Chrome
 - Version 97.0.4692.70

**Comment by s-amundson** [comment]
Resolved js issues that caused this problem.
