### ISSUE TITLE
JOAD Class functionality

### ISSUE THREAD

**Issue by Silventar** [s-amundson/wpa_2p1#38]
**The JOAD class is invite-only and is session based.

**
- Need field in Student table: JOAD

- To attend JOAD classes, students must have a safety class and be approved by an instructor (marked as JOAD)

- Session classes cost $xxx.xx and consist of (n) classes on 'x dates.

- We need to be able to set dates for a session and have them schedule a student who registers for them.

- Pin shoots are a special JOAD class, to register a student must have a safety class date and be JOAD approved.

-need the ability to change a class date for a session for unforeseen  issues like rain, etc.

**Comment by s-amundson** [comment]
Implemented on test server. 
JOAD checkbox shows up when editing a student if student is of JOAD age. 
Info paragraphs show up for those that are not staff or have a student that is marked JOAD.

Pin shoots have still to be implemented. Should a student be required to be JOAD approved to participate? This would hinder students from other clubs from attending our pin shoots.

**Comment by s-amundson** [comment]
JOAD registrations implemented on live server, JOAD event (pin shoot) functionality implemented. Need to add classes and events to calendar.
