### ISSUE TITLE
Board member add instructor/student day of event

### ISSUE THREAD

**Issue by Silventar** [s-amundson/wpa_2p1#52]
**Is your feature request related to a problem? Please describe.**

 Often, we need to add an instructor to a class who was not normally scheduled to be there because they are filling for lack of instructors. Would like to be able to easily add them to a class the day of. 

Additionally, I would like to be able to add students the day of as well. Although we should not be doing it, we should have the functionality for rare cases.

**Describe the solution you'd like**
 This should be an option available to board members only that show in the class check in list.

**Comment by s-amundson** [comment]
Same as issue #48 updated code to add after class has started.
