### ISSUE TITLE
JOAD attendance is not sticking

### ISSUE THREAD

**Issue by Silventar** [s-amundson/wpa_2p1#61]
**Describe the bug**
JOAD attendance is not sticking

**To Reproduce**
Open Joad
Open session 1
Open March 1 attendance
Check attendance

**Expected behavior**
Iattwndance should stay when navigating away and coming back. But it doesn't, unless we got a signature.

**Comment by s-amundson** [comment]
Found issue in js, fixed. updated attendance of students.
