### ISSUE TITLE
Unsuccessful payment status is unclear

### ISSUE THREAD

**Issue by Silventar** [s-amundson/wpa_2p1#71]
**Describe the bug**
See attached image if customers phone. Status of start should read "unsucessful." Additionally, the unregister button should not displayed as it makes the customer believe they are registered.

![20220402_091512.jpg](https://user-images.githubusercontent.com/17868374/161392911-357857dc-7292-4cd7-8e4d-01e962da3c53.jpg)

![d3ae135a84881870ee2f9fce5412d1cf71a5668b-14.jpg](https://user-images.githubusercontent.com/17868374/161392922-5bbe32fc-efeb-4061-8022-f738bb96218f.jpg)

**Comment by s-amundson** [comment]
Set the payment status to show up as "Unsuccessful" rather then "Start". Changed column from "Unregister" to Unregister/Cancel" added appropriate label to checkbox. Changed button text from "Unregister" to Unregister/Cancel" .
