### ISSUE TITLE
Running tab of registrations vs attending in student profile 

### ISSUE THREAD

**Issue by Silventar** [s-amundson/wpa_2p1#73]
**Is your feature request related to a problem? Please describe.**
Currently, we think we are seeing some people registering for multiple returnee classes and not showing up for many of them. This prevents people who want to be there from registering.

**Describe the solution you'd like**
I'd like to have two running total fields in the student profile: Classes Registered and classes Attended. These should be counts of classes in the past, not upcoming classes. These should  also display on the class checkin list so that the gatekeeper can easily see the problem registrants. Optionally, it may be good to be able to click a button to see a list of dates to see if there are patterns.

There should also be a list of the student's upcoming class registrations in their profile that instructors can see (if it isn't already.

In the students profile list, only available to staff, or perhaps board members, should be a contact student button that allows an email to be sent to the student. There should be a dropdown list of pre-written emails, one of which we would draft and title for this specific purpose. This email should be editable by the sender.

**Additional context**
This solution may reduce the number of no-shows when problem individuals are found. At least, it will make them aware that two are, possibly unintentionally, causing problems.

**Comment by s-amundson** [comment]
Board members can now click on a link in the check-in page and view most of a student's profile (same result as clicking on a student in the student list). This profile page includes how many classes a student registered for and how many attended as well as upcoming classes that a student has registered for.
