### ISSUE TITLE
Switch signup and clear buttons on waiver page and de-emphasize clear

### ISSUE THREAD

**Issue by Silventar** [s-amundson/wpa_2p1#80]
**Is your feature request related to a problem? Please describe.**

 When signing the waiver, students tend to hit the clear button instead of the sign up button. They automatically go they automatically go to the right side for some reason.

**Describe the solution you'd like**

Can we switch the 2 buttons and also change the clear button from a large button to just a gray text link?

**Comment by s-amundson** [comment]
Buttons switched, clear button changed to outline button
