### ISSUE TITLE
Add PCR to covid policy

### ISSUE THREAD

**Issue by Silventar** [s-amundson/wpa_2p1#88]
We need to add PCR to the covid policy:

Covid-19 Policy

In order to protect our volunteers and participants, all participants and their accompanying family members are required to show either 1) proof of vaccination or 2) proof of a negative PCR Covid-19 test within the previous 48 hours. All participants are required to bring and wear a mask for the entire duration of the class. No refunds are given for failure to comply with our COVID Policy.

**Comment by s-amundson** [comment]
Policy updated
