### ISSUE TITLE
Classes that students can't sign up for.

### ISSUE THREAD

**Issue by s-amundson** [s-amundson/wpa_2p1#90]
create a class that student's can't sign up for but instructors can. For example vets.

**Comment by s-amundson** [comment]
Could create a combined class that has 0 and 0 for limits and set state as full.

**Comment by Silventar** [comment]
Excellent solution!

Shoot well!
Andrew Robertson
RobertsonArchery.com

**Comment by s-amundson** [comment]
Created a 'special' class type, this class type doesn't show up on the class calendar for students but does show up for instructors.
