### ISSUE TITLE
Email to JOAD is not going to JOAD Instructors

### ISSUE THREAD

**Issue by Silventar** [s-amundson/wpa_2p1#91]
**Describe the bug**
 When sending out an email to the joad group via the registration website, joad instructors are not receiving a copy of the email. Students are, but not instructors.

**Expected behavior**
  Is there an ability to mark instructors as joad instructors? If not, can we add that and can they be included in the emails?

**Comment by s-amundson** [comment]
Marked instructors as JOAD students. This should resolve the issue.
