### ISSUE TITLE
JOAD: Autofill

### ISSUE THREAD

**Issue by Silventar** [s-amundson/wpa_2p1#93]
**Is your feature request related to a problem? Please describe.**
 When setting the attendance for pinshoots, it takes time to fill in the data. It would be great if the data was already prefilled from their student profile if they have already done a pinshoot.

**Describe the solution you'd like**
 The student profile should have information about the last about the last pinshoot they did, including the distance, target size, and most recent pin earned.  This data should prefill the pinshoot attendance information if it is available in a student profile.

**Comment by s-amundson** [comment]
Adding initial data from prior pin shoot. 
When checking in students only field needed to be filled out by staff is the attendance checkbox. The rest can and I think should be filled out by student/guardian. Adding instructions for staff initial: 'Staff responsibility is to mark the student as attending. All other fields are optional and the responsibility of the student/guardian.'
Adding instruction for student/guardian: 'Please fill out all fields below or verify that the information filled out is correct'
