### ISSUE TITLE
JOAD: Student List

### ISSUE THREAD

**Issue by Silventar** [s-amundson/wpa_2p1#94]
**Is your feature request related to a problem? Please describe.**

There is no way to call up a list of all JOAD student profiles. 

**Describe the solution you'd like**

There should be a searchable JOAD Student List in the JOAD section of the menu. This list should include columns for all Pinshoot information.

**Comment by s-amundson** [comment]
Created, making ordered list by last name. Pinshoot information shows for completed pin shoots( stars calculated). Showing pin shoot with max stars followed by max score. Would it be preferred if it was last event?
